name: Build and Deploy
on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Deploy project
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: deploy